server:
  port: 8081


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://101.43.9.197:3306/questions?characterEncoding=utf8&useUnicode=true&useSSL=true
    username: questions
    password: lzq@@951201

logging:
  config: classpath:logback-lab-dev.xml

aio:
  knife4j:
    title: Lab在线接口文档 - 0.1.0
    group: ''
    description: Lab 在线接口文档
    version: 1.0
    contact:
      name: yiidii
      url: 'https://blog.yiidii.cn'
      email: 'yd1141309981@gmail.com '
  log:
    path: logs-dev
    level: info