server:
  port: 8081


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.9.197:3306/questions?characterEncoding=utf8&useUnicode=true&useSSL=true
    username: questions
    password: lzq@@951201

logging:
  config: classpath:logback-lab-dev.xml

aio:
  knife4j:
    title: Lab在线接口文档 - 0.1.0
    group: ''
    description: Lab 在线接口文档
    version: 1.0
    contact:
      name: aio
      url: 'http://api.kidoneself.com:8081/doc.html#/home'
      email: 'kiddoneself@gmail.com '
  log:
    path: logs-dev
    level: info